---
title: "Mia EDA"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
library(ggplot2)
```

```{r}
og_ultimate_data <- read_csv("/Users/miazottoli/Desktop/M244-Final-JVM/data/ultimate_college_championship.csv")
```

```{r}
ultimate_data <- read_csv("/Users/miazottoli/Desktop/M244-Final-JVM/data/ultimate_college_championship.csv") %>%
  mutate(across(c(level, gender, division, team_name), as.factor)) %>%
  mutate(school = str_split_i(team_name, " ", 1)) %>%
  mutate(school = ifelse(str_detect(team_name, "St Olaf"), "St Olaf", school)) %>%
  mutate(school = ifelse(str_detect(team_name, "North Carolina"), "North Carolina", school)) %>%
  mutate(school = ifelse(str_detect(team_name, "Cal Poly"), "Cal Poly SLO", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "British Columbia"), "British Columbia", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Western Washington"), "Western Washington", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Penn State"), "Penn State", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "San Diego"), "UCSD", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Lewis"), "Lewis & Clark", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Colorado State"), "Colorado State", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Oklahoma Christian"), "Oklahoma Christian", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Binghamton"), "SUNY Binghamton", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Santa Bar"), "UCSB", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Santa Cr"), "USCS", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Colorado College"), "Colorado College", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Missouri S"), "Missouri S&T", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Holyoke"), "Mount Holyoke", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "NC State"), "NC State", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Oregon State"), "Oregon State", school))  %>%
  mutate(school = ifelse(str_detect(team_name, "Washington University"), "Washington University", school))
```

```{r}
ggplot(ultimate_data, aes(x = gender, y = plus_minus, fill = gender)) +
  geom_boxplot() +
  labs(
    title = "Gender vs. Player's +/- Score",
    x = "Gender",
    y = "Player's +/- Score"
  ) +
  theme_minimal()
```

```{r}
ggplot(ultimate_data, aes(x = level, y = plus_minus, fill = level)) +
  geom_violin(trim = FALSE) +
  labs(
    title = "Player's +/- Score for Division 1 vs Division 3",
    x = "Division",
    y = "Player's +/- Score"
  ) +
  scale_fill_manual(values = c("Division 1" = "blue", "Division 3" = "pink")) + 
  theme_minimal()
```

```{r}
women_ultimate_data <- ultimate_data %>%
  filter(gender == "Women")
```

```{r}
ggplot(women_ultimate_data, aes(x = level, y = plus_minus, fill = level)) +
  geom_violin(trim = FALSE) +
  labs(
    title = "Player's +/- Score for Division 1 vs Division 3 Women",
    x = "Division",
    y = "Player's +/- Score"
  ) +
  scale_fill_manual(values = c("Division 1" = "blue", "Division 3" = "pink")) + 
  theme_minimal()
```

```{r}
men_ultimate_data <- ultimate_data %>%
  filter(gender == "Men")
```

```{r}
ggplot(men_ultimate_data, aes(x = level, y = plus_minus, fill = level)) +
  geom_violin(trim = FALSE) +
  labs(
    title = "Player's +/- Score for Division 1 vs Division 3 Men",
    x = "Division",
    y = "Player's +/- Score"
  ) +
  scale_fill_manual(values = c("Division 1" = "blue", "Division 3" = "pink")) + 
  theme_minimal()
```

```{r}
unique_team_names <- unique(og_ultimate_data$team_name)
unique_team_names
```
